### PR TITLE
unit test pet service

### LINKED ISSUE #148: Unit Test for Pet Service
Unit test for functionality so far in PetService

### PR DESCRIPTION
**Pull request by bwruan**

### CODE REVIEW

**Review by jruan1580 — CHANGES_REQUESTED** [review]
Once you address this other PR, will need to add DTO mapper unit tests

**Comment by jruan1580** [comment]
Did not add unit tests for mappers

**Review by jruan1580 — CHANGES_REQUESTED** [review]
did not add unit test for mapper

**Comment by bwruan** [comment]
done

**Review by jruan1580 — APPROVED** [review]

**Pull request merged**
